### ISSUE TITLE
Python version recommendation

### ISSUE THREAD

**Issue by brennagibbons** [CitrineInformatics/learn-citrination#14]
The main page recommends python3, but the tutorials (at least Advanced Queries print statements) need python2. @maxhutch

**Comment by maxhutch** [comment]
The tutorials should support both python2 and python3.  @eantono, can you wrap your `print` with paren in the AdvancedQueries?  I'm sorry that I missed that on review :cry:

**Comment by carenac** [comment]
fixed in updated notebooks
