### ISSUE TITLE
pyCC 4 compatible notebooks

### ISSUE THREAD

**Issue by Setogit** [CitrineInformatics/learn-citrination#23]
pyCC 4.0.0 is released.   What's the migration plan for the tutorial notebooks?  For new users, it'd be nice to have 4.0.0 notebooks sooner than later.

I went over the tutorial notebooks with pyCC 4.0.0.  The edit was relatively straightforward (thanks to the nice and short change log) but,  as a new user, a bit confusing to learn less-clean 3.x API and migrate to 4.0.0 at the same time.

**Comment by Setogit** [comment]
PR #25 replaced PR #24

**Comment by maxhutch** [comment]
Resolved in #25
